### ISSUE TITLE
Found deprecated code at line #77 of arrays.jl

### ISSUE THREAD

**Issue by nick3499** [Ivo-Balbaert/start_julia#1]
In your file [arrays.jl](https://github.com/Ivo-Balbaert/start_julia/blob/master/Chapter%202/arrays.jl) at line #77 you have `println(cell(4))` but in Julia 0.5.2 that instruction returns `WARNING: cell(dims::Integer...) is deprecated, use Array{Any}(dims...) instead.` So I changed `println(cell(4))` to `println(Array{Any}(4))` and my new instruction returns `Any[#undef,#undef,#undef,#undef]`. A possible solution for updating line #77 to Julia 0.5.2.

**Comment by Ivo-Balbaert** [comment]
ok, corrected
